export const AUTH_CONSTANT = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    AUTH_CHECK: 'AUTH_CHECK',
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',
}